version: '3'
services:
  naorobot_dev:
    build: 
      context: .
      dockerfile: ./prod_docker
    image: devrobot:test
    ports:
      - "1180:8080"
    environment:
      - "ENV:PROD"
  naorobot_test:
    build: 
      context: .
      dockerfile: ./test_docker
    image: testrobot:test
    ports:
      - "8011:8080"
    environment:
       - "ENV:TEST"